"""Generate schedule triggers from manifests.

- local-cron  -> macOS launchd LaunchAgent plist (StartCalendarInterval).
  launchd uses LOCAL timezone and runs missed jobs on wake, so the manifest's
  local cron maps directly — no tz conversion.
- github-actions -> Actions workflow with the cron converted to UTC (Actions
  cron is UTC only); DST is approximated (see note emitted to the user).
"""
from __future__ import annotations

import plistlib
import sys
from datetime import datetime
from itertools import product
from pathlib import Path
from zoneinfo import ZoneInfo

import config

LABEL_PREFIX = "com.my-automations"
LAUNCHD_DIR = config.REPO_ROOT / "deploy" / "launchd"
WORKFLOWS_DIR = config.REPO_ROOT / ".github" / "workflows"

CRON_FIELDS = ["minute", "hour", "day", "month", "weekday"]
LAUNCHD_KEYS = {"minute": "Minute", "hour": "Hour", "day": "Day",
                "month": "Month", "weekday": "Weekday"}


class DeployError(Exception):
    pass


def _parse_cron(schedule: str) -> dict[str, list[int]]:
    """Parse '<m> <h> <dom> <mon> <dow>'. Supports ints, '*', and comma lists.

    Returns {field: [values]}; '*' fields are omitted (wildcard).
    Raises on ranges/steps (unsupported) so we never silently mis-schedule.
    """
    parts = schedule.split()
    if len(parts) != 5:
        raise DeployError(f"cron must have 5 fields, got {len(parts)!r}: {schedule!r}")
    out: dict[str, list[int]] = {}
    for field, raw in zip(CRON_FIELDS, parts):
        if raw == "*":
            continue
        if any(c in raw for c in "-/"):
            raise DeployError(
                f"cron field {field}={raw!r} uses ranges/steps — not supported "
                f"by the generator; use explicit values or '*'."
            )
        out[field] = [int(x) for x in raw.split(",")]
    return out


def _calendar_intervals(schedule: str) -> list[dict]:
    """Build launchd StartCalendarInterval entries (one per value combo)."""
    fields = _parse_cron(schedule)
    if not fields:
        raise DeployError("schedule has no concrete fields (all '*').")
    keys = list(fields.keys())
    combos = product(*(fields[k] for k in keys))
    return [{LAUNCHD_KEYS[k]: v for k, v in zip(keys, combo)} for combo in combos]


def launchd_plist(m) -> tuple[str, str, Path]:
    """Return (label, plist_xml, suggested_path) for a local-cron automation."""
    if not m.schedule:
        raise DeployError(f"{m.id}: no schedule to deploy.")
    label = f"{LABEL_PREFIX}.{m.id}"
    intervals = _calendar_intervals(m.schedule)
    log_out = str(config.LOGS_DIR / f"{m.id}.scheduled.out")
    log_err = str(config.LOGS_DIR / f"{m.id}.scheduled.err")

    plist = {
        "Label": label,
        # login shell so PATH finds python3/claude/security; cd to repo.
        "ProgramArguments": [
            "/bin/bash", "-lc",
            f'cd {config.REPO_ROOT!s} && exec {sys.executable} cli/auto run {m.id} --trigger schedule',
        ],
        "WorkingDirectory": str(config.REPO_ROOT),
        "StandardOutPath": log_out,
        "StandardErrorPath": log_err,
        "RunAtLoad": False,
    }
    plist["StartCalendarInterval"] = intervals if len(intervals) > 1 else intervals[0]
    xml = plistlib.dumps(plist).decode("utf-8")
    suggested = Path.home() / "Library" / "LaunchAgents" / f"{label}.plist"
    return label, xml, suggested


def _to_utc_cron(schedule: str, tz: str | None) -> tuple[str, str]:
    """Convert a local cron to a UTC cron for GitHub Actions. Returns (utc_cron, note)."""
    fields = schedule.split()
    if not tz:
        return schedule, "no tz given — assuming schedule is already UTC."
    offset = ZoneInfo(tz).utcoffset(datetime(2026, 1, 15))  # winter ref; DST approx
    offset_h = int(offset.total_seconds() // 3600)
    note = (f"converted {tz}->UTC using a fixed {offset_h:+d}h offset; "
            f"DST shifts by 1h are NOT tracked (Actions cron is best-effort anyway).")
    if fields[1] == "*":
        return schedule, "hour is '*'; left unchanged. " + note
    hour = (int(fields[1]) - offset_h) % 24
    fields[1] = str(hour)
    return " ".join(fields), note


def actions_workflow(m) -> tuple[str, str]:
    """Return (yaml, note) for a github-actions automation."""
    if not m.schedule:
        raise DeployError(f"{m.id}: no schedule to deploy.")
    utc_cron, note = _to_utc_cron(m.schedule, m.tz)
    secrets_env = "\n".join(
        f"          {s}: ${{{{ secrets.{s} }}}}" for s in m.secrets
    )
    yaml = f"""# Generated by `auto deploy {m.id}`. Edit the manifest, not this file.
name: {m.id}
on:
  schedule:
    - cron: "{utc_cron}"   # UTC; {note}
  workflow_dispatch: {{}}
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run {m.id}
        env:
{secrets_env if secrets_env else '          NOOP: "1"'}
        run: python cli/auto run {m.id} --trigger schedule
"""
    return yaml, note
